### PR TITLE
Update the resource stubs to include unified_mode

### PR DESCRIPTION
**Pull request by MarkGibbons**
# Description

Add unified mode to the resource stubs

## Issues Resolved
none
## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ramereth — CHANGES_REQUESTED** [review]
Looks like we have an error in the `Gemfile` which should just be removed IMHO.

**Comment by MarkGibbons** [comment]
Gemfile nuked.

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [1.0.0](https://github.com/sous-chefs/dnsmasq/releases/tag/1.0.0)

**Pull request merged**
